FROM openjdk:17-jdk-slim

# 애플리케이션 코드를 /app 디렉토리에 복사
COPY . /app
WORKDIR /app

# Gradle wrapper 실행 권한 부여
RUN chmod +x ./gradlew

# 애플리케이션이 사용하는 포트를 노출
EXPOSE 8080

# 애플리케이션을 실행하는 명령어
ENTRYPOINT ["./gradlew", "bootRun"]