version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: shop-review-db
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - ./.env
    networks:
      - app_net
    restart: always
    cap_add:
      - SYS_NICE
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p${DB_PASSWORD} || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: shop-review-app
    ports:
      - "8080:8080"
    environment:
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    env_file:
      - ./.env
    networks:
      - app_net

volumes:
  db_data:

networks:
  app_net: